spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://
    username:
    password:

custom:
  secret:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  cors:
    domain:
