spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres

custom:
  secret:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  cors:
    domain: http//:localhost:3000
  cloudinary:
    name: dt212gr4m
    api-key: 839826362311982
    api-secret: neFJEViwPCkJPMba1bfH1Jqlb4Q