server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          pool_size: 10
          autoReconnect: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  swagger-ui:
    path: /swagger